### ISSUE TITLE
Regression in GitHub API Plugin 1.109 breaking jenkinsci's GHPRB plugin

### ISSUE THREAD

**Issue by Panajev** [github-api/github-api#776] opened 2020-04-06 15:59 UTC
**Describe the bug**
After updating GitHub API Plugin to 1.109 the post receive hooks would not cause a GitHub Pull Request Builder based job to execute. Reverting to 1.106, restarting Jenkins, and ensuring the commit hook fired again would start the job once more

**To Reproduce**
1. Update GitHub API Plugin from 1.106 to 1.109
2. Create new PR for a repository with a post receive commit hook setup (there is a matching Jenkins job configured with the jenkinsci GitHub Pull Request Builder plugin) so that the hook fires (or you can use a PR comment to do the same if configured in your GHPRB setup)

**Expected behavior**
Jenkins job is started

**Actual behavior**
Jenkins job is not started. Reverting GitHub Api Plugin to 1.106 fixes the issue

**Desktop (please complete the following information):**
 - OS: CentOS
 - Browser: N/A
 - Version: Jenkins plugin 1.109
 - Jenkins: 2.230

**Comment by bitwiseman** [comment] 2020-04-06 16:39
Duplicate of #775

**Comment by bitwiseman** [comment] 2020-04-06 16:41
Keep this open until fix is released.

**Comment by ereesmanAR** [comment] 2020-04-06 18:51
@bitwiseman what are the steps to fix this for users of GitHub Pull Request Builder plugin?

**Closed** 2020-04-07 00:17 UTC
